"""
Engineering Report Page
"""

import io

import streamlit as st
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)


def create_report_pdf(dataset, ai_insights):

    buffer = io.BytesIO()

    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=45,
        leftMargin=45,
        topMargin=45,
        bottomMargin=45,
    )

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER

    heading_style = styles["Heading2"]
    body_style = styles["BodyText"]

    story = []

    # Title
    story.append(
        Paragraph(
            "Field Return Failure Analysis Report",
            title_style,
        )
    )

    story.append(Spacer(1, 20))

    # Dataset information
    story.append(
        Paragraph(
            f"<b>Total Records:</b> {len(dataset):,}",
            body_style,
        )
    )

    story.append(
        Paragraph(
            f"<b>Total Columns:</b> {len(dataset.columns)}",
            body_style,
        )
    )

    story.append(Spacer(1, 20))

    # AI analysis
    for line in ai_insights.split("\n"):

        line = line.strip()

        if not line:
            story.append(Spacer(1, 8))
            continue

        if line.startswith("#"):

            heading = line.lstrip("#").strip()

            story.append(
                Paragraph(
                    heading,
                    heading_style,
                )
            )

        else:

            clean_line = (
                line
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
            )

            story.append(
                Paragraph(
                    clean_line,
                    body_style,
                )
            )

    story.append(Spacer(1, 25))

    story.append(
        Paragraph(
            "Generated by Field Return Failure Mining",
            body_style,
        )
    )

    document.build(story)

    buffer.seek(0)

    return buffer.getvalue()


def render_report_page():

    st.title("📄 Engineering Report")

    st.caption(
        "Generate a downloadable engineering report from the analyzed dataset."
    )

    if "dataset" not in st.session_state:

        st.warning("Please upload a dataset first.")
        return

    if "ai_insights" not in st.session_state:

        st.info(
            "Please generate AI Insights first."
        )
        return

    dataset = st.session_state["dataset"]
    ai_insights = st.session_state["ai_insights"]

    st.success(
        "AI analysis is ready. Your engineering report can now be generated."
    )

    col1, col2 = st.columns(2)

    with col1:
        st.metric(
            "Records Analyzed",
            f"{len(dataset):,}",
        )

    with col2:
        st.metric(
            "Report Status",
            "Ready",
        )

    st.divider()

    st.subheader("Report Preview")

    st.markdown(ai_insights)

    st.divider()

    # Generate PDF
    pdf_data = create_report_pdf(
        dataset,
        ai_insights,
    )

    st.download_button(
        label="📥 Download Engineering Report (PDF)",
        data=pdf_data,
        file_name="field_return_engineering_report.pdf",
        mime="application/pdf",
        type="primary",
        use_container_width=True,
    )